GET http://localhost:8000/available_fields/

###

POST http://localhost:8000/generate_dataset/ HTTP/1.1
content-type: application/json

{
"fields":{
        "id":{
                "custom_col_name": "moje id"
        },
        "gender":{
                "custom_col_name":"plec",
                "equal_weight":true,
                "blanck_chance":0
                },
        "age":{
                    "custom_col_name":"Wiek",
                    "low_lim":0,
                    "up_lim":100,
                    "equal_weight":true,
                    "blanck_chance":0
            },
        "first_name":{
                    "custom_col_name":"imiona",
                    "double_name_chance":15,
                    "equal_weight":false,
                    "unfit_to_gen":true,
                    "blanck_chance":0
                    },
        "last_name":{
                    "custom_col_name":"Nazwisko",
                    "double_name_chance":15,
                    "equal_weight":false,
                    "unfit_to_gen":true,
                    "blanck_chance":0
                    },
        "voivodeship":{
                        "custom_col_name":"Wojewodztwo",
                    "equal_weight": false,
                    "blanck_chance":50
                    },
        "postcode":{
                "custom_col_name":"kod pocztowy",
                    "independently": false,
                    "blanck_chance":0
                    },
        "sportstatus":{
                    "custom_col_name":"status sportowca",
                    "independently":false,
                    "without_none":false,
                    "equal_weight":false,
                    "blanck_chance":0
                    },
        "languages":{
                "custom_col_name":null,
                "equal_weight":false,
                "without_none":false,
                "blanck_chance":0
        },
        "edu_level":{
                "custom_col_name":null,
                "equal_weight":false,
                "without_none":false,
                "blanck_chance":0
        }
        },
"general":{
        "rows":10,
        "response_format":"json" 
        }
}

###

POST http://localhost:8000/generate_dataset/ HTTP/1.1
content-type: application/json

{
"fields":{
        "voivodeship":{
                "equal_weight":false
        }},
"general":{
        "rows":3,
        "response_format":"json" 
        }
}

###

POST http://localhost:8000/generate_dataset/ HTTP/1.1
content-type: application/json

{
"fields":{
        "sportstatus":{
                "custom_col_name":"status",
                "independently":false
                    },
        "sportdiscipline":{
                "custom_col_name":"dyscyplina",
                "independently":false,
                "blanck_chance":0
                }
        },
"general":{
        "rows":10,
        "response_format":"json" 
        }
}